
version: '2'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'

  typo3:
    image: mulgo/typo3-toolchain:<%=cleanTypo3Version %>
    build:
      context: .
    environment:
      TYPO3_CONTEXT: "Development"
    ports:
      - 80:80
    volumes:
      - .:/var/www/site

volumes:
  mysql:

networks:
  net:
    driver: bridge